[package]
name = "mio-gui"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
authors = ["Reza Rasoulzadeh"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/RezaRasoulzadeh/mio-gui"
description = "A native, cross-platform Rust GUI framework with RTL and LTR as equal, first-class layout directions."

[dependencies]
arboard = { version = "=3.6.1", default-features = false, features = ["wayland-data-control"] }
bytemuck = { version = "=1.25.2", features = ["derive"] }
cosmic-text = "=0.15.0"
pollster = "=1.0.1"
unicode-segmentation = "=1.13.3"
unicode-script = "=0.5.8"
wgpu = "=30.0.0"
winit = "=0.30.13"